Repository boostcampwm-2024/iOS06-molio, pull requests merged in 2024-11, with the labels that each got.

#7 feat: 디자인 시스템 설정 (폰트, 이미지, 텍스트)
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Assets.xcassets/AlbumCoverSample.imageset/Contents.json
  Molio/Resource/Assets.xcassets/AlbumCoverSample.imageset/sample.png
  Molio/Resource/Assets.xcassets/background.colorset/Contents.json
  Molio/Resource/Assets.xcassets/logo.imageset/Contents.json
  Molio/Resource/Assets.xcassets/logo.imageset/logo_molio.png
  Molio/Resource/Assets.xcassets/main.colorset/Contents.json
  Molio/Resource/Assets.xcassets/mainLighter.colorset/Contents.json
  Molio/Resource/Assets.xcassets/tag.colorset/Contents.json
  Molio/Resource/Font/Pretendard-Black.otf
  Molio/Resource/Font/Pretendard-Bold.otf
  Molio/Resource/Font/Pretendard-ExtraBold.otf
  Molio/Resource/Font/Pretendard-ExtraLight.otf
  Molio/Resource/Font/Pretendard-Light.otf
  Molio/Resource/Font/Pretendard-Medium.otf
  Molio/Resource/Font/Pretendard-Regular.otf
  Molio/Resource/Font/Pretendard-SemiBold.otf
  Molio/Resource/Font/Pretendard-Thin.otf
  Molio/Resource/Info.plist
  Molio/Source/DesignSystem/PretendardFontName.swift
  Molio/Source/Util/Extension/Extension.swift
  Molio/Source/Util/Extension/SwiftUI/Font+Extension.swift
  Molio/Source/Util/Extension/SwiftUI/Text+Extension.swift
  Molio/Source/Util/Extension/UIKit/UILabel+Extension.swift
Labels: feat

#10 feat: MusicKit 권한 설정 세팅 & ISRC로 애플 뮤직 음악 정보 검색
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/MusicKitService.swift
  Molio/Source/Data/DataSource/Network/Network.swift
Labels: feat

#13 feat: 메인 플레이리스트 음악 정보 카드 화면 UI 작업
  .github/PULL_REQUEST_TEMPLATE.md
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Base.lproj/Main.storyboard
  Molio/Resource/Info.plist
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Presentation/Common/Component/CircleMenuButton.swift
  Molio/Source/Presentation/Common/Component/Component.swift
  Molio/Source/Presentation/SwipeMusic/View/MusicTagView.swift
  Molio/Source/Presentation/SwipeMusic/View/MusicTrackView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Util/Extension/UIKit/UIColor+Extension.swift
Labels: feat

#17 feat: 현재 듣는 음악의 Artwork에 따른 배경색 지정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/SwipeMusic/SwipeMusicViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#18 feat: 카드에 스와이프 동작 추가
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#20 setting: 유닛 테스트 타겟 생성
  Molio.xcodeproj/project.pbxproj
  MolioTests/MolioTests.swift
Labels: setting

#27 feat: 네트워크 레이어 구성
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DTO/ExternalIDsDTO.swift
  Molio/Source/Data/DTO/SpotifyAccessTokenResponseDTO.swift
  Molio/Source/Data/DTO/TrackDTO.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/EndPoint.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/HTTPMethod.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/HTTPResponseStatusCode.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/NetworkError.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/NetworkProvider.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/DefaultSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/MockSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPI.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAccessTokenProvider/MockSpotifyAccessTokenProvider.swift
  Molio/Source/Data/DataSource/Network/SpotifyAccessTokenProvider/SpotifyAccessTokenProvider.swift
  Molio/Source/Data/DataSource/Network/SpotifyTokenProvider/MockSpotifyTokenProvider.swift
  Molio/Source/Data/DataSource/Network/SpotifyTokenProvider/SpotifyAuthorizationAPI.swift
  Molio/Source/Data/DataSource/Network/SpotifyTokenProvider/SpotifyTokenProvider.swift
  Molio/Source/Data/Repository/DefaultMusicRepository.swift
  Molio/Source/Data/Repository/MockSpotifyRepository.swift
  Molio/Source/Domain/RepositoryInterface/SpotifyRepository.swift
  Molio/Source/Domain/UseCase/FetchRecommendedSongsUseCase/FetchRecommendedSongsUseCase.swift
  Molio/Source/Presentation/Common/ViewController.swift
  MolioTests/MolioTests.swift
  MolioTests/NetworkProviderTests.swift
  MolioTests/Test Double/Dummy/RecommendationsResponseDTODummy.swift
  MolioTests/Test Double/Dummy/SpotifyAccessTokenResponseDTODummy.swift
  MolioTests/Test Double/Mock/MockURLProtocol.swift
Labels: feat

#33 feat: MusicKit에서 받아온 음악 데이터를 카드 화면에 표시한다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/DataSource/Network/ImageFetchService/DafaultImageProvider.swift
  Molio/Source/Data/DataSource/Network/ImageFetchService/ImageFecthError.swift
  Molio/Source/Data/DataSource/Network/ImageFetchService/ImageFetchService.swift
  Molio/Source/Data/Repository/DefaultImageRepository.swift
  Molio/Source/Data/Repository/DefaultMusicRepository.swift
  Molio/Source/DesignSystem/PretendardFontName.swift
  Molio/Source/Domain/RepositoryInterface/ImageRepository.swift
  Molio/Source/Domain/UseCase/FetchImageUsecase/Implementation/DefaultFetchImageUseCase.swift
  Molio/Source/Domain/UseCase/FetchImageUsecase/Protocol/FetchImageUseCase.swift
  Molio/Source/Presentation/Common/Base/InputOutputViewModel.swift
  Molio/Source/Presentation/SwipeMusic/Model/SwipeMusicTrackModel.swift
  Molio/Source/Presentation/SwipeMusic/View/MusicCardView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicPlayer.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  Molio/Source/Util/Protocol/AudioPlayer.swift
Labels: feat

#30 feat: MusicDeck 구현하기 (#29)
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/Entity/MusicDeck/MusicDeck.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/Entity/MusicFilterProvider/MockMusicFilterProvider.swift
  Molio/Source/Domain/Entity/MusicFilterProvider/MusicFilterProvider.swift
  MolioTests/DeckTests.swift
Labels: feat

#45 feat: Package.resolved 파일 추가
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bugfix

#48 feat: 스와이프와 버튼을 동기화 합니다.
  Molio/Source/Presentation/Common/Component/CircleMenuButton.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
Labels: feat

#50 chore: 앱 아이콘 적용
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Molio/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Molio/Resource/Assets.xcassets/logo.imageset/Contents.json
  Molio/Resource/Assets.xcassets/logo.imageset/logo_molio.png
Labels: feat

#43 feat: MusicDeck과 프레젠테이션 계층 연결하기
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Domain/Entity/MusicDeck/MusicDeck.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicPlayer.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  Molio/Source/Util/Protocol/AudioPlayer.swift
Labels: feat

#49 feat: Playlist Entity 정의 및 PlaylistRepository 구현
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/LocalStorage/LocalStorage.swift
  Molio/Source/Data/DataSource/LocalStorage/PersistenceManager.swift
  Molio/Source/Data/Model/DTO/ExternalIDsDTO.swift
  Molio/Source/Data/Model/DTO/PlaylistDTO.swift
  Molio/Source/Data/Model/DTO/RecommendationsRequestDTO.swift
  Molio/Source/Data/Model/DTO/RecommendationsResponseDTO.swift
  Molio/Source/Data/Model/DTO/SpotifyAccessTokenResponseDTO.swift
  Molio/Source/Data/Model/DTO/TrackDTO.swift
  Molio/Source/Data/Model/DataModel/MolioModel.xcdatamodeld/MolioModel.xcdatamodel/contents
  Molio/Source/Data/Model/DataModel/MolioPlaylist+CoreDataClass.swift
  Molio/Source/Data/Model/DataModel/MolioPlaylist+CoreDataProperties.swift
  Molio/Source/Data/Model/DataModel/PlaylistModel.xcdatamodeld/Playlist.xcdatamodel/contents
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/RepositoryInterface/PlaylistRepository.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
  MolioTests/Test Double/Dummy/SpotifyAccessTokenResponseDTODummy.swift
Labels: feat

#51 bugfix: Core Data 모델 파일, 시크릿 configuration 파일 참조 수정
  Molio.xcodeproj/project.pbxproj
Labels: bugfix

#54 bugfix: Swipe Music 화면 오류 수정
  Molio/Source/Presentation/SwipeMusic/View/MusicCardView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
Labels: bugfix

#57 refactor: DefaultMusicRepository, DefaultFetchMusicsUseCase 이름 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/Repository/DefaultRecommendedMusicRepository.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/RepositoryInterface/RecommendedMusicRepository.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Implementation/DefaultFetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Protocol/FetchRecommendedMusicUseCase.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  MolioTests/DeckTests.swift
Labels: enhancement

#65 feat: 로그인 화면을 구현해야한다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/Login/View/LoginViewController.swift
Labels: feat

#62 feat: 필터 화면 UI 구현
  .swiftlint.yml
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/PersistenceManager.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/EndPoint.swift
  Molio/Source/Data/DataSource/Network/NetworkProvider/NetworkProvider.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/DefaultSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/MockSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPI.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyTokenProvider/SpotifyAuthorizationAPI.swift
  Molio/Source/Data/Model/DTO/SpotifyAvailableGenreSeedsDTO.swift
  Molio/Source/Data/Model/DataModel/Playlist+CoreDataProperties.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Data/Repository/DefaultRecommendedMusicRepository.swift
  Molio/Source/Data/Repository/MockSpotifyRepository.swift
  Molio/Source/Domain/Entity/MusicDeck/MusicDeck.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/Entity/MusicFilter.swift
  Molio/Source/Domain/Entity/MusicFilterProvider/MockMusicFilterProvider.swift
  Molio/Source/Domain/Entity/MusicGenre.swift
  Molio/Source/Domain/RepositoryInterface/RecommendedMusicRepository.swift
  Molio/Source/Domain/RepositoryInterface/SpotifyRepository.swift
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Implementation/DefaultFetchAvailableGenresUseCase.swift
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Implementation/MockDefaultFetchAvailableGenresUseCase.swift
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Protocol/FetchAvailableGenresUseCase.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Implementation/DefaultFetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Protocol/FetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/FetchRecommendedSongsUseCase/FetchRecommendedSongsUseCase.swift
  Molio/Source/Presentation/MusicFilter/View/FilterTag.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterView.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/MusicFilter/View/TagLayout.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Util/Extension/SwiftUI/Image+Extension.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
  MolioTests/NetworkProviderTests.swift
  MolioTests/SpotifyTokenProviderTests.swift
  MolioTests/Test Double/Dummy/SpotifyAccessTokenResponseDTODummy.swift
  MolioTests/Test Double/Dummy/SpotifyAvailableGenreSeedsDTODummy.swift
Labels: feat

#72 feat: 플레이리스트 생성 모달 UI 추가
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Implementation/DefaultCreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Protocol/CreatePlaylistUseCase.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/SwipeMusic/View/CreatePlaylistView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Util/Extension/UIKit/UIViewController/presentCustomSheet.swift
  Molio/Source/Util/Extension/UIKit/addGradientBackground.swift
Labels: feat

#75 feat: PublishCurrentPlaylistUseCase 프로토콜과 구현체 만들기
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/PublishCurrentPlaylistUseCase.swift
  MolioTests/PublishCurrentPlaylistUseCaseTests.swift
Labels: feat

#79 feat: CreatePlaylistUseCase, ChangeCurrentPlaylistUseCase 추가 및 플레이리스트 생성 화면과 연결
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataError.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/RepositoryInterface/PlaylistRepository.swift
  Molio/Source/Domain/UseCase/ChangeCurrentPlaylistIUseCase/ChangeCurrentPlaylistIUseCase.swift
  Molio/Source/Domain/UseCase/ChangeCurrentPlaylistIUseCase/DefaultChangeCurrentPlaylistIUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Implementation/DefaultCreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Protocol/CreatePlaylistUseCase.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/CreatePlaylist/CreatePlaylistView.swift
  Molio/Source/Presentation/CreatePlaylist/CreatePlaylistViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#80 feat: 애플 로그인을 파이어베이스를 통해 받아온 값을 저장합니다.
  .gitignore
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Molio.entitlements
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseError.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseService.swift
  Molio/Source/Data/Repository/DefaultSignAppleRepository.swift
  Molio/Source/Domain/Entity/Auth/AppleAuthInfo.swift
  Molio/Source/Domain/RepositoryInterface/SignAppleRepository.swift
  Molio/Source/Domain/UseCase/SignInAppleUseCase/DefaultSignInAppleUseCase.swift
  Molio/Source/Domain/UseCase/SignInAppleUseCase/SignInAppleUseCase.swift
  Molio/Source/Presentation/Login/View/LoginViewController.swift
  Molio/Source/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: feat

#118 setting: 깃허브 액션 CI 자동화 세팅
  .github/workflows/CI_BUILD.yml
  .github/workflows/CI_TEST.yml
  .gitignore
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  MolioTests/DefaultCurrentPlaylistRepositoryTests.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
  run_build.sh
  run_tests.sh
Labels: setting

#78 refactor: DIContainer 구현
  .github/workflows/CI_BUILD.yml
  .github/workflows/CI_TEST.yml
  .swiftlint.yml
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/App/DIContainer.swift
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/DataSource/Network/ImageFetchService/DefaultImageFetchService.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/DefaultSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyTokenProvider/DefaultSpotifyTokenProvider.swift
  Molio/Source/Data/Repository/DefaultImageRepository.swift
  Molio/Source/Data/Repository/DefaultRecommendedMusicRepository.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/UseCase/ChangeCurrentPlaylistIUseCase/DefaultChangeCurrentPlaylistIUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Implementation/DefaultCreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Implementation/DefaultFetchAvailableGenresUseCase.swift
  Molio/Source/Domain/UseCase/FetchImageUsecase/Implementation/DefaultFetchImageUseCase.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Implementation/DefaultFetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/CreatePlaylist/CreatePlaylistView.swift
  Molio/Source/Presentation/CreatePlaylist/CreatePlaylistViewModel.swift
  Molio/Source/Presentation/Login/View/LoginViewController.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterView.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  MolioTests/DeckTests.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
Labels: enhancement

#122 setting: 워크플로우 수정 테스트
  .github/workflows/CI_BUILD.yml
  .github/workflows/CI_TEST.yml
Labels: setting

#121 feat: 마이 몰리오(플레이리스트에 있는 음악 듣는 화면)의 음악 재생 컨트롤 기능 추가
  .swiftlint.yml
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/Entity/MolioMusic+sample.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Implementation/DefaultCreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Presentation/PlaylistDetail/PlaylistDetailListItemView.swift
  Molio/Source/Presentation/PlaylistDetail/PlaylistDetailViewAudioPlayerControl.swift
  Molio/Source/Presentation/PlaylistDetail/PlaylistDetailViewList.swift
  Molio/Source/Presentation/PlaylistDetail/View/AudioPlayerControlView.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicCellView.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicListView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#126 feat: PublishCurrentPlaylistUseCase 복구 (#119)
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  MolioTests/PublishCurrentPlaylistUseCaseTests.swift
Labels: bugfix

#124 feat: PublishAllMusicInCurrentPlaylistUseCase 프로토콜 정의와 구현체 작성 (#82)
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Domain/UseCase/PublishAllMusicInCurrentPlaylistUseCase/DefaultPublishAllMusicInCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishAllMusicInCurrentPlaylistUseCase/PublishAllMusicInCurrentPlaylistUseCase.swift
  MolioTests/PublishAllMusicInCurrentPlaylistUseCaseTests.swift
Labels: feat

#131 feat: 기기 화면 크기에 따라 다른 개수의 노래 정보를 표시하는 뷰를 생성합니다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/ExportPlaylist/ExportMusicListPage.swift
  Molio/Source/Presentation/ExportPlaylist/ExportPlaylistItemView.swift
  Molio/Source/Presentation/ExportPlaylist/ExportPlaylistView.swift
Labels: feat

#138 feat: 생성된 뷰들의 이미지를 생성하고 저장할 수 있다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/ExportPlaylist/ExportMusicListPage.swift
  Molio/Source/Presentation/ExportPlaylist/ExportPlaylistItemView.swift
  Molio/Source/Presentation/ExportPlaylist/ExportPlaylistView.swift
  Molio/Source/Presentation/ExportPlaylist/Model/ExportMusicItem.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistItemView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistPageView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistView.swift
  Molio/Source/Presentation/ExportPlaylist/ViewModel/ExportPlaylistViewModel.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
Labels: feat

#168 feat: 로그인 유무에 따라 시작화면이 달라집니다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/UserDefaults/AuthLocalStorage.swift
  Molio/Source/Data/DataSource/LocalStorage/UserDefaults/DefaultAuthLocalStorage.swift
  Molio/Source/Data/Repository/DefaultAuthStateRepository.swift
  Molio/Source/Data/Repository/DefaultSignAppleRepository.swift
  Molio/Source/Domain/Entity/Auth/AuthMode.swift
  Molio/Source/Domain/Entity/Auth/AuthSelection.swift
  Molio/Source/Domain/RepositoryInterface/AuthStateRepository.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/DefaultManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/ManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/SignInAppleUseCase/DefaultSignInAppleUseCase.swift
  Molio/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Molio/Source/Presentation/Splash/View/SplashViewController.swift
  Molio/Source/Presentation/Splash/ViewModel/SplahViewModel.swift
Labels: feat

#169 feat: 필터 수정 Core Data 반영 & 변경된 필터로 추천 노래 불러오기
  .github/workflows/CI_TEST.yml
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataError.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/PersistenceManager.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/MockSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPI.swift
  Molio/Source/Data/Repository/CoreDataPlaylistRepository.swift
  Molio/Source/Data/Repository/DefaultRecommendedMusicRepository.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/Entity/MusicDeck/MusicDeck.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/RepositoryInterface/PlaylistRepository.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/MockPublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UpdatePlaylistUseCase/DefaultUpdatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UpdatePlaylistUseCase/UpdatePlaylistUseCase.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/MusicFilter/View/TagLayout.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  Molio/Source/Util/Extension/UIKit/UIViewController/showAlert.swift
  MolioTests/DeckTests.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
  MolioTests/MusicDeckTests.swift
  MolioTests/MusicFilterViewModelTests.swift
  MolioTests/PublishAllMusicInCurrentPlaylistUseCaseTests.swift
  MolioTests/PublishCurrentPlaylistUseCaseTests.swift
  MolioTests/Test Double/Mock/DataSource/MockNetworkProvider.swift
  MolioTests/Test Double/Mock/DataSource/MockURLProtocol.swift
  MolioTests/Test Double/Mock/Repository/MockCurrentPlaylistRepository.swift
  MolioTests/Test Double/Mock/Repository/MockPlaylistRepository.swift
  MolioTests/Test Double/Mock/UseCase/MockPublishCurrentPlaylistUseCase.swift
  MolioTests/Test Double/Mock/UseCase/MockUpdatePlaylistUseCase.swift
Labels: feat

#183 feat: UITabbarController를 생성합니다.
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Assets.xcassets/personCircle.imageset/Contents.json
  Molio/Resource/Assets.xcassets/personCircle.imageset/personCircle.png
  Molio/Resource/Assets.xcassets/personCircle.imageset/personCircle@2x.png
  Molio/Resource/Assets.xcassets/personCircle.imageset/personCircle@3x.png
  Molio/Source/Presentation/Community/CommunityViewController.swift
  Molio/Source/Presentation/Login/View/LoginViewController.swift
  Molio/Source/Presentation/Splash/View/SplashViewController.swift
  Molio/Source/Presentation/Splash/ViewModel/SplahViewModel.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
Labels: feat

#184 feat: FirebaseStorageManager 추가
  Molio.xcodeproj/project.pbxproj
  Molio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Molio/Source/Data/DataSource/Network/FirebaseService/Error/FirebaseError.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Error/FirebaseStorageError.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Manager/FirebaseStorageManager.swift
  MolioTests/FirebaseStorageManagerTests.swift
Labels: feat

#180 feat: FirestoreManager 정의하기
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/FirestoreManager/FirestoreEntity.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/FirestoreError.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/FirestoreManager.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/MolioPlaylist+Decodable.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/MolioPlaylist+FirestoreEntity.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/Entity/MusicFilter.swift
  Molio/Source/Domain/Entity/MusicGenre.swift
  MolioTests/FirestoreManagerTests.swift
Labels: feat

#191 refactor: CoreDataPlaylistRepository => CoreDataPlaylistStorage로 변경
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataPlaylistStorage.swift
  Molio/Source/Data/DataSource/LocalStorage/Protocol/AuthLocalStorage.swift
  Molio/Source/Data/DataSource/LocalStorage/Protocol/PlaylistLocalStorage.swift
  Molio/Source/Domain/RepositoryInterface/CRUDProtocol.swift
  MolioTests/CoreDataPlaylistStorageTests.swift
  MolioTests/DefaultCurrentPlaylistRepositoryTests.swift
Labels: enhancement

#186 feat: 설정화면 UI 작업구현
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Assets.xcassets/spacingBackground.colorset/Contents.json
  Molio/Source/Presentation/Setting/ProfileItemView.swift
  Molio/Source/Presentation/Setting/SettingTextItemView.swift
  Molio/Source/Presentation/Setting/SettingView.swift
Labels: feat

#197 feat: 플레이리스트 상세 화면 & 플레이리스트 불러오기 & 노래 담기 로직 연동
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataPlaylistStorage.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/Entity/MusicFilterProvider/MockMusicFilterProvider.swift
  Molio/Source/Domain/Entity/MusicFilterProvider/MusicFilterProvider.swift
  Molio/Source/Domain/RepositoryInterface/PlaylistRepository.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/AddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/DefaultAddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UpdatePlaylistUseCase/DefaultUpdatePlaylistUseCase.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicCellView.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicListView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
  MolioTests/FirebaseStorageManagerTests.swift
  MolioTests/PublishAllMusicInCurrentPlaylistUseCaseTests.swift
  MolioTests/PublishCurrentPlaylistUseCaseTests.swift
  MolioTests/Test Double/Mock/Repository/MockPlaylistRepository.swift
Labels: feat

#202 feat: 플레이리스트 내보내기 관련 화면 UI
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Assets.xcassets/appleMusicLogo.imageset/Contents.json
  Molio/Resource/Assets.xcassets/appleMusicLogo.imageset/appleMusicLogo.png
  Molio/Resource/Assets.xcassets/appleMusicLogo.imageset/appleMusicLogo@2x.png
  Molio/Resource/Assets.xcassets/appleMusicLogo.imageset/appleMusicLogo@3x.png
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/ExportPlaylist/Model/ExportPlatform.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportAppleMusicPlaylist/ExportAppleMusicCompletionView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/ExportPlaylistImageView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/PlaylistImageMusicItem.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/PlaylistImagePage.swift
  Molio/Source/Presentation/ExportPlaylist/View/PlatformSelectionView.swift
  Molio/Source/Presentation/ExportPlaylist/ViewModel/ExportPlaylistImageViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
Labels: feat

#209 feat: FirebaseFollowRelationService 프로토콜 추가 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseFollowRelationService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/FollowRelationService.swift
  Molio/Source/Data/Model/DTO/FollowRelationDTO.swift
  Molio/Source/Data/Model/DTO/MolioUserDTO.swift
  MolioTests/FirebaseFollowRelationServiceTests.swift
  MolioTests/FirebaseUserServiceTests.swift
Labels: feat

#211 feat: UserUseCase 프로토콜 구현 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/Entity/MolioUser.swift
  Molio/Source/Domain/Entity/Music/MolioMusic+sample.swift
  Molio/Source/Domain/Entity/Music/MolioMusic.swift
  Molio/Source/Domain/Entity/Music/MusicFilter.swift
  Molio/Source/Domain/Entity/Music/MusicGenre.swift
  Molio/Source/Domain/Entity/Music/RecommendationRequestEntity.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  MolioTests/DefaultUserUseCaseTests.swift
Labels: feat

#214 feat: 사용자 정보 변경 화면 UI 작업
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Assets.xcassets/textFieldBackground.colorset/Contents.json
  Molio/Source/Presentation/MyInfo/View/DescriptionTextFieldView.swift
  Molio/Source/Presentation/MyInfo/View/MyInfoView.swift
  Molio/Source/Presentation/MyInfo/View/NickNameTextFieldView.swift
  Molio/Source/Presentation/MyInfo/ViewModel/MyInfoViewModel.swift
  Molio/Source/Presentation/Setting/SettingView.swift
Labels: feat

#213 feat: CommuniytUseCase 프로토콜 구현 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseAuthService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/AuthService.swift
  Molio/Source/Domain/Entity/MolioFollowRelation.swift
  Molio/Source/Domain/Entity/MolioMusic+sample.swift
  Molio/Source/Domain/Entity/MolioMusic.swift
  Molio/Source/Domain/Entity/MolioUser.swift
  Molio/Source/Domain/Entity/MusicFilter.swift
  Molio/Source/Domain/Entity/MusicGenre.swift
  Molio/Source/Domain/Entity/RecommendationRequestEntity.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/CommunityUseCase.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/DefaultCommunityUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  MolioTests/DefaultCommnunityUseCaseTests.swift
  MolioTests/DefaultUserUseCaseTests.swift
  MolioTests/Test Double/Mock/DataSource/MockAuthService.swift
  MolioTests/Test Double/Mock/DataSource/MockFollowRelationService.swift
Labels: feat

#218 refactor: SettingView, MyInfoView UIHostingController 래퍼 구현
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/MyInfo/View/MyInfoView.swift
  Molio/Source/Presentation/MyInfo/View/MyInfoViewController.swift
  Molio/Source/Presentation/MyInfo/ViewModel/MyInfoViewModel.swift
  Molio/Source/Presentation/Setting/SettingView.swift
  Molio/Source/Presentation/Setting/SettingViewController.swift
Labels: refactor

#216 feat: 플레이리스트 내보내기 시 UI 처리 & 애플 뮤직 구독 확인
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitError.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitService.swift
  Molio/Source/Domain/UseCase/CheckAppleMusicSubscriptionUseCase/CheckAppleMusicSubscriptionUseCase.swift
  Molio/Source/Domain/UseCase/CheckAppleMusicSubscriptionUseCase/DefaultCheckAppleMusicSubscriptionUseCase.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/ExportPlaylist/View/PlatformSelection/PlatformSelectionView.swift
  Molio/Source/Presentation/ExportPlaylist/View/PlatformSelection/PlatformSelectionViewController.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicListView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Util/Extension/UIKit/UIViewController/presentCustomSheet.swift
Labels: feat

#222 feat: CurrentUserIdUseCase 프로토콜 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/UseCase/CurrentUserIdUseCase/CurrentUserIdUseCase.swift
  Molio/Source/Domain/UseCase/CurrentUserIdUseCase/DefaultCurrentUserIdUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/DefaultManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/ManageAuthenticationUseCase.swift
  MolioTests/DefaultCurrentUserIdUseCaseTests.swift
Labels: feat

#229 feat: ManagePlaylistUseCase 프로토콜 구현 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/ManageMyPlaylistUseCase.swift
  MolioTests/DefaultManageMyPlaylistUseCaseTests.swift
  MolioTests/Test Double/Mock/Repository/MockPlaylistRepository.swift
Labels: feat

#231 feat: CommunityUseCase 프로토콜 구현 및 구현체 정의
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/UseCase/CommunityUseCase/CommunityUseCase.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/DefaultCommunityUseCase.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/DefaultFollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/FollowRelationUseCase.swift
  MolioTests/DefaultCommnunityUseCaseTests.swift
  MolioTests/DefaultFollowRelationUseCaseTests.swift
  MolioTests/PublishCurrentPlaylistUseCaseTests.swift
Labels: feat

#236 feat: 유저(친구, 나)의 프로필 화면 추가
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseFollowRelationService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseUserService.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/Entity/MusicFilter.swift
  Molio/Source/Presentation/Community/CommunityViewController.swift
  Molio/Source/Presentation/Community/FollowRelationButton.swift
  Molio/Source/Presentation/Community/FollowRelationType.swift
  Molio/Source/Presentation/Community/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfileViewModel.swift
Labels: feat

#235 feat: 애플 뮤직 플레이리스트 내보내기
  .swiftlint.yml
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseFollowRelationService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Manager/FirebaseStorageManager.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitError.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitService.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/DefaultCommunityUseCase.swift
  Molio/Source/Domain/UseCase/ExportAppleMusicPlaylistUseCase/DefaultExportAppleMusicPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ExportAppleMusicPlaylistUseCase/ExportAppleMusicPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportAppleMusicPlaylist/ExportAppleMusicPlaylistView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportAppleMusicPlaylist/ExportAppleMusicPlaylistViewController.swift
  Molio/Source/Presentation/ExportPlaylist/View/PlatformSelection/PlatformSelectionView.swift
  Molio/Source/Presentation/ExportPlaylist/View/PlatformSelection/PlatformSelectionViewController.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Util/Extension/UIKit/UIViewController/presentCustomSheet.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
Labels: feat

#238 feat: (친구, 나) 사용자의 팔로우, 팔로워 목록 보기 기능 추가
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/Entity/MolioFollower.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/DefaultFollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/FollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  Molio/Source/Presentation/Community/CommunityViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationListView.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewModel.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
  MolioTests/DefaultFetchPlaylistUseCaseTests.swift
  MolioTests/DefaultFollowRelationUseCaseTests.swift
  MolioTests/FirebaseFollowRelationServiceTests.swift
  MolioTests/FirebaseStorageManagerTests.swift
  MolioTests/FirebaseUserServiceTests.swift
  MolioTests/FirestoreManagerTests.swift
  MolioTests/FirestorePlaylistServiceTests.swift
Labels: feat

#242 feat: 설정화면 기능 구현
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseAuthService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Error/FirebaseAuthError.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/AuthService.swift
  Molio/Source/Data/Repository/DefaultAuthStateRepository.swift
  Molio/Source/Data/Repository/DefaultSignAppleRepository.swift
  Molio/Source/Domain/RepositoryInterface/AuthStateRepository.swift
  Molio/Source/Domain/RepositoryInterface/SignAppleRepository.swift
  Molio/Source/Domain/UseCase/CurrentUserIdUseCase/DefaultCurrentUserIdUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/DefaultManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/ManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/SignInAppleUseCase/DefaultSignInAppleUseCase.swift
  Molio/Source/Domain/UseCase/SignInAppleUseCase/SignInAppleUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Presentation/Community/CommunityViewController.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Molio/Source/Presentation/Setting/PrivacyPolicyView.swift
  Molio/Source/Presentation/Setting/ProfileItemView.swift
  Molio/Source/Presentation/Setting/SettingTextItemView.swift
  Molio/Source/Presentation/Setting/SettingView.swift
  Molio/Source/Presentation/Setting/SettingViewController.swift
  Molio/Source/Presentation/Setting/SettingViewModel.swift
  Molio/Source/Presentation/Setting/TermsAndConditionView.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
  MolioTests/DefaultCurrentUserIdUseCaseTests.swift
  MolioTests/Test Double/Mock/DataSource/MockAuthService.swift
Labels: feat

#239 feat: 플레이리스트 이미지 내보내기 화면 연결 & 애플뮤직 딥링크
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitService.swift
  Molio/Source/Domain/UseCase/AppleMusicUseCase/AppleMusicUseCase.swift
  Molio/Source/Domain/UseCase/AppleMusicUseCase/DefaultAppleMusicUseCase.swift
  Molio/Source/Domain/UseCase/CheckAppleMusicSubscriptionUseCase/CheckAppleMusicSubscriptionUseCase.swift
  Molio/Source/Domain/UseCase/CheckAppleMusicSubscriptionUseCase/DefaultCheckAppleMusicSubscriptionUseCase.swift
  Molio/Source/Domain/UseCase/ExportAppleMusicPlaylistUseCase/DefaultExportAppleMusicPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ExportAppleMusicPlaylistUseCase/ExportAppleMusicPlaylistUseCase.swift
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportAppleMusicPlaylist/ExportAppleMusicPlaylistView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportAppleMusicPlaylist/ExportAppleMusicPlaylistViewController.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/ExportPlaylistImageView.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/ExportPlaylistImageViewController.swift
  Molio/Source/Presentation/ExportPlaylist/ViewModel/ExportPlaylistImageViewModel.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
  Molio/Source/Util/Extension/UIKit/UIButton+Extension.swift
Labels: feat

#241 feat: 친구 플리에 있는 노래 내 플리로 가져오기
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/FetchPlaylistUseCase.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/Delegate/ExportFriendsMusicToMyPlaylistDelegate.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/Delegate/FriendPlaylistDetailHostingViewController+ExportFriendsMusicToMyPlaylistDelegate.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailHostingViewController.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/SelectPlaylistToExportFriendMusicView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/FriendPlaylistDetailViewModel.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/SelectPlaylistToExportFriendMusicViewModel.swift
Labels: feat

#250 feat: 로그인 시 파이어베이스에 유저 정보 저장
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/PlaylistService/FirestorePlaylistService.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/AddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/DefaultAddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  Molio/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  MolioTests/DefaultUserUseCaseTests.swift
Labels: feat

#251 feat: 플레이리스트 상세 화면 유즈케이스 정리 & 내 플레이리스트 목록 불러오기 시 문제 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataPlaylistStorage.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/AddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/AddMusicToPlaylistUseCase/DefaultAddMusicToPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/DefaultFetchAllPlaylistsUseCase.swift
  Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/FetchAllPlaylistsUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Presentation/PlaylistDetail/View/AudioPlayerControlView.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
Labels: refactor

#254 refactor: 플레이리스트 선택 및 생성 기능의 UseCase 수정 / 플레이리스트 선택 및 생성 ViewModel 통합.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/UseCase/ChangeCurrentPlaylistIUseCase/ChangeCurrentPlaylistIUseCase.swift
  Molio/Source/Domain/UseCase/ChangeCurrentPlaylistIUseCase/DefaultChangeCurrentPlaylistIUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Implementation/DefaultCreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/CreatePlaylistUsecase/Protocol/CreatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/ManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishAllMusicInCurrentPlaylistUseCase/DefaultPublishAllMusicInCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishAllMusicInCurrentPlaylistUseCase/PublishAllMusicInCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/DefaultPublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/MockPublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/PublishCurrentPlaylistUseCase/PublishCurrentPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UpdatePlaylistUseCase/DefaultUpdatePlaylistUseCase.swift
  Molio/Source/Domain/UseCase/UpdatePlaylistUseCase/UpdatePlaylistUseCase.swift
  Molio/Source/Presentation/CreatePlaylist/CreatePlaylistViewModel.swift
  Molio/Source/Presentation/ManagePlaylist/CreatePlaylistView.swift
  Molio/Source/Presentation/ManagePlaylist/ManagePlaylistViewModel.swift
  Molio/Source/Presentation/ManagePlaylist/SelectPlaylistView.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  MolioTests/DefaultManageMyPlaylistUseCaseTests.swift
  MolioTests/PublishAllMusicInCurrentPlaylistUseCaseTests.swift
  MolioTests/Test Double/Mock/UseCase/MockPublishCurrentPlaylistUseCase.swift
  MolioTests/Test Double/Mock/UseCase/MockUpdatePlaylistUseCase.swift
Labels: refactor
