Repository boostcampwm-2024/iOS06-molio, pull requests merged in 2024-12, with the labels that each got.

#260 feat: 유저 검색 기능
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseUserService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/UserService.swift
  Molio/Source/Data/Model/DTO/MolioUserDTO.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/Entity/MolioUser.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/DefaultCommunityUseCase.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/DefaultFollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  Molio/Source/Presentation/Common/Component/DefaultProfile.swift
  Molio/Source/Presentation/Community/CommunityViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationListView.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewModel.swift
  Molio/Source/Presentation/ManagePlaylist/ManagePlaylistViewModel.swift
  Molio/Source/Presentation/SearchUser/View/SearchBar.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserView.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserViewController.swift
  Molio/Source/Presentation/SearchUser/View/UserInfoCell.swift
  Molio/Source/Presentation/SearchUser/ViewModel/SearchUserViewModel.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
  MolioTests/DefaultCommnunityUseCaseTests.swift
  MolioTests/MusicFilterViewModelTests.swift
  MolioTests/Test Double/Mock/Repository/MockPlaylistRepository.swift
  MolioTests/Test Double/Mock/UseCase/MockCurrentUserIdUseCase.swift
  MolioTests/Test Double/Mock/UseCase/MockManagePlaylistUseCase.swift
Labels: feat

#262 feat: 사용자는 내 정보를 수정할 수 있다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseAuthService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseUserService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Manager/FirebaseStorageManager.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/UserService.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/ProfileImageUpdateType.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  Molio/Source/Presentation/MyInfo/View/MyInfoView.swift
  Molio/Source/Presentation/MyInfo/View/MyInfoViewController.swift
  Molio/Source/Presentation/MyInfo/View/ProfileImageView.swift
  Molio/Source/Presentation/MyInfo/ViewModel/MyInfoViewModel.swift
  Molio/Source/Presentation/Setting/SettingView.swift
  Molio/Source/Presentation/Setting/SettingViewController.swift
Labels: feat

#263 refactor: 내 프로필 화면에서 내 플레이리스트 목록 보기 기능 로직 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Domain/UseCase/CurrentUserIdUseCase/DefaultCurrentUserIdUseCase.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationListView.swift
  Molio/Source/Presentation/Community/ProfileImageView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewModel.swift
  Molio/Source/Presentation/MyInfo/View/ChangeProfileImageView.swift
  Molio/Source/Presentation/MyInfo/View/MyInfoView.swift
  Molio/Source/Presentation/Setting/SettingViewController.swift
Labels: refactor

#264 feat: FriendPlaylistDetailView에 UseCase 연결
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Domain/Entity/MolioMusic.swift
  Molio/Source/Presentation/AudioPlayerControl/AudioPlayerControlView.swift
  Molio/Source/Presentation/AudioPlayerControl/AudioPlayerControlViewModel.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailHostingViewController.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/SelectPlaylistToExportFriendMusicView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/FriendPlaylistDetailViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/AudioPlayerControlView.swift
  Molio/Source/Presentation/PlaylistDetail/View/MusicListView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
Labels: refactor

#276 feat: MusicDeck 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/DefaultRandomMusicDeck.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
Labels: bugfix

#282 feat: 친구 요청을 수락하는 화면 UI를 그려야 한다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/Community/Notification/NotificationView.swift
  Molio/Source/Presentation/Community/Notification/NotificationViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewModel.swift
Labels: feat

#280 bugfix: 유저의 닉네임이 업데이트 되지 않는 문제 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/Mapper/MolioUserMapper.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
Labels: bugfix

#281 bugfix: Core Data 플레이리스트 관련 오류 수정 & 생성 시트 글래스모피즘 적용
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataPlaylistStorage.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/Entity/MusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/RepositoryInterface/PlaylistRepository.swift
  Molio/Source/Domain/RepositoryInterface/RealPlaylistRepository.swift
  Molio/Source/Domain/UseCase/CommunityUseCase/DefaultCommunityUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/ManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailHostingViewController.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/FriendPlaylistDetailViewModel.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/SelectPlaylistToExportFriendMusicViewModel.swift
  Molio/Source/Presentation/ManagePlaylist/CreatePlaylistView.swift
  Molio/Source/Presentation/ManagePlaylist/View/CreatePlaylist/CreatePlaylistView.swift
  Molio/Source/Presentation/ManagePlaylist/View/CreatePlaylist/CreatePlaylistViewController.swift
  Molio/Source/Presentation/ManagePlaylist/View/SelectPlaylist/SelectPlaylistView.swift
  Molio/Source/Presentation/ManagePlaylist/View/SelectPlaylist/SelectPlaylistViewController.swift
  Molio/Source/Presentation/ManagePlaylist/ViewModel/ManagePlaylistViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  MolioTests/DefaultCommnunityUseCaseTests.swift
  MolioTests/DefaultManageMyPlaylistUseCaseTests.swift
  MolioTests/Test Double/Mock/Repository/MockPlaylistRepository.swift
  MolioTests/Test Double/Mock/UseCase/MockCurrentUserIdUseCase.swift
Labels: bugfix

#284 refactor: 카드 스와이프 시작 위치 수정
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: refactor

#286 bugfix: 친구의 플레이리스트 안의 노래를 누를 시 재생하도록 하기
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailView.swift
Labels: feat

#292 feat: 사용자의 팔로우, 팔로잉 UI 구현 및 팔로우 및 언팔로우 기능 추가
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseFollowRelationService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/FirebaseUserService.swift
  Molio/Source/Domain/Entity/MolioFollower.swift
  Molio/Source/Domain/Entity/MolioUser.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/DefaultFollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/FollowRelationUseCase/FollowRelationUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/DefaultUserUseCase.swift
  Molio/Source/Domain/UseCase/UserUseCase/UserUseCase.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationListView.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewModel.swift
  Molio/Source/Presentation/Community/FollowRelation/Model/FollowRelationType.swift
  Molio/Source/Presentation/Community/FollowRelation/View/FollowRelationButton.swift
  Molio/Source/Presentation/Community/FollowRelation/View/FollowRelationListView.swift
  Molio/Source/Presentation/Community/FollowRelation/View/FollowRelationViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/ViewModel/FollowRelationViewModel.swift
  Molio/Source/Presentation/Community/Notification/NotificationViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/Model/ProfileType.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/View/ProfileImageView.swift
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/ViewController/CommunityViewController.swift
  Molio/Source/Presentation/Community/UserProfile/ViewController/FriendProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/ViewController/UserProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/ViewModel/UserProfileViewModel.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/FriendPlaylistDetailHostingViewController.swift
  Molio/Source/Presentation/SearchUser/View/SearchBar.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserView.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserViewController.swift
  Molio/Source/Presentation/SearchUser/View/UserInfoCell.swift
  Molio/Source/Presentation/SearchUser/ViewModel/SearchUserViewModel.swift
  Molio/Source/Presentation/Setting/View/PrivacyPolicyView.swift
  Molio/Source/Presentation/Setting/View/ProfileItemView.swift
  Molio/Source/Presentation/Setting/View/SettingTextItemView.swift
  Molio/Source/Presentation/Setting/View/SettingView.swift
  Molio/Source/Presentation/Setting/View/TermsAndConditionView.swift
  Molio/Source/Presentation/Setting/ViewController/SettingViewController.swift
  Molio/Source/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: feat

#293 feat: 플레이리스트 데이터 정렬 문제 수정
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseAuthService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Error/FirebaseAuthError.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/DefaultRandomMusicDeck.swift
  Molio/Source/Domain/UseCase/CurrentUserIdUseCase/DefaultCurrentUserIdUseCase.swift
  Molio/Source/Presentation/Community/FollowRelation/FollowRelationViewController.swift
  Molio/Source/Presentation/Community/FollowRelation/Model/FollowRelationType.swift
  Molio/Source/Presentation/Community/UserProfile/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/View/ProfileImageView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/View/SelectPlaylistToExportFriendMusicView.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/FriendPlaylistDetailViewModel.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Util/Mapper/MolioPlaylistMapper.swift
Labels: bugfix

#295 refactor: 화면 이상 버그 수정
  Molio/Source/Presentation/Community/Notification/NotificationView.swift
  Molio/Source/Presentation/Community/Notification/NotificationViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
Labels: bugfix

#296 bugfix: 검색 화면 키보드 내리기
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/SearchUser/View/SearchUserView.swift
  Molio/Source/Presentation/SearchUser/ViewModel/SearchUserViewModel.swift
  Molio/Source/Util/Extension/SwiftUI/View+Extension.swift
Labels: bugfix

#302 enhancement: 플리에 이미 있는 노래는 추가하지 않는다. (#301)
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
Labels: enhancement

#303 feat: 플레이리스트가 하나도 없을시 기본 플레이리스트를 생성한다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/Splash/View/SplashViewController.swift
  Molio/Source/Presentation/Splash/ViewModel/SplahViewModel.swift
  Molio/Source/Presentation/Splash/ViewModel/SplashViewModel.swift
Labels: feat

#305 refactor: 설정 화면 UI 수정
  Molio/Source/Presentation/Setting/View/ProfileItemView.swift
  Molio/Source/Presentation/Setting/View/SettingTextItemView.swift
Labels: refactor

#306 bugfix: 커뮤니티 회원 프로필 관련 버그 수정
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
  Molio/Source/Presentation/Community/UserProfile/ViewController/FriendProfileViewController.swift
  Molio/Source/Presentation/Community/UserProfile/ViewController/UserProfileViewController.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
Labels: bugfix

#308 feat: 탭바 디자인 및 레이아웃 개선
  Molio/Source/Presentation/AudioPlayerControl/AudioPlayerControlViewModel.swift
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
  Molio/Source/Presentation/ManagePlaylist/View/SelectPlaylist/SelectPlaylistViewController.swift
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailViewController.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/Tabbar/MolioTabBarController.swift
Labels: enhancement

#313 feat: 게스트 상태인 경우 검색화면 이용을 제한하고 로그인을 할 수 있어야 한다.
  Molio.xcodeproj/project.pbxproj
  Molio/Source/Presentation/Common/Component/BasicButton.swift
  Molio/Source/Presentation/SearchUser/View/LoginRequiredView.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserView.swift
  Molio/Source/Presentation/SearchUser/View/SearchUserViewController.swift
  Molio/Source/Presentation/SearchUser/ViewModel/SearchUserViewModel.swift
Labels: feat

#314 feat: 노래 추천 & 필터 기능 Spotify API -> MusicKit으로 변경
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/AppDelegate.swift
  Molio/Source/Data/DataSource/LocalStorage/CoreData/CoreDataPlaylistStorage.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/MolioPlaylist+Decodable.swift
  Molio/Source/Data/DataSource/Network/FirestoreManager/MolioPlaylist+FirestoreEntity.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/MusicKitService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/DefaultSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/MockSpotifyAPIService.swift
  Molio/Source/Data/DataSource/Network/SpotifyAPIService/SpotifyAPIService.swift
  Molio/Source/Data/Model/DTO/RecommendationsRequestDTO.swift
  Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
  Molio/Source/Data/Repository/DefaultRecommendedMusicRepository.swift
  Molio/Source/Domain/Entity/MolioPlaylist.swift
  Molio/Source/Domain/Entity/MusicFilter.swift
  Molio/Source/Domain/Entity/MusicGenre.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/DefaultRandomMusicDeck.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/RandomMusicDeck.swift
  Molio/Source/Domain/Entity/RecommendationRequestEntity.swift
  Molio/Source/Domain/RepositoryInterface/RecommendedMusicRepository.swift
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Implementation/MockDefaultFetchAvailableGenresUseCase.swift
  Molio/Source/Domain/UseCase/FetchMusicsUseCase/Protocol/FetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/FetchRecommendedMusicUseCase/DefaultFetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/FetchRecommendedMusicUseCase/FetchRecommendedMusicUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/DefaultManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/ManageMyPlaylistUseCase/ManageMyPlaylistUseCase.swift
  Molio/Source/Domain/UseCase/RealPlaylistUseCase/DefaultFetchPlaylistUseCase.swift
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterView.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/MusicFilter/ViewModel/MusicFilterViewModel.swift
  Molio/Source/Presentation/PlaylistDetail/ViewModel/PlaylistDetailViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  Molio/Source/Util/Mapper/MolioPlaylistMapper.swift
  MolioTests/CoreDataPlaylistStorageTests.swift
  MolioTests/DefaultCommnunityUseCaseTests.swift
  MolioTests/DefaultManageMyPlaylistUseCaseTests.swift
  MolioTests/DefaultPlaylistRepositoryTests.swift
  MolioTests/MusicFilterViewModelTests.swift
  MolioTests/Test Double/Mock/UseCase/MockManagePlaylistUseCase.swift
Labels: enhancement

#318 refactor: ScrollView offset에 따른 NavigationBar 색상 변경
  Molio/Source/App/SceneDelegate.swift
Labels: refactor

#320 setting: Localization에 한국어 추가
  Molio/Resource/Info.plist
Labels: enhancement

#323 bugfix: 음악 카드 제목 텍스트 잘리지 않도록 수정
  Molio/Source/Presentation/SwipeMusic/View/MusicCardView.swift
Labels: enhancement

#325 refactor: 팔로잉, 팔로워 위치 변경
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
Labels: refactor

#327 setting: 앱 display name 변경
  Molio.xcodeproj/project.pbxproj
Labels: setting

#330 feat: 메인노래 카드 준비 이전 로딩바 구현
  Molio/Source/Domain/Entity/RandomMusicDeck/DefaultRandomMusicDeck.swift
  Molio/Source/Domain/Entity/RandomMusicDeck/RandomMusicDeck.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
Labels: feat

#329 feat: 음악 카드 회전 애니메이션 적용
  Molio/Source/Presentation/PlaylistDetail/View/PlaylistDetailView.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#333 feat: 필터 화면 전환 방식 내비게이션 -> present 로 수정
  Molio/Source/Domain/UseCase/FetchAvailableGenresUseCase/Implementation/MockDefaultFetchAvailableGenresUseCase.swift
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/ExportPlaylistImageView.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterView.swift
  Molio/Source/Presentation/MusicFilter/View/MusicFilterViewController.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#337 refactor: 카드 스와이프 시 UI 개선
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: refactor

#335 bugfix: 내 프로필을 남의 프로필이라 인식하는 오류 해결
  Molio/Source/Presentation/Community/FollowRelation/View/FollowRelationViewController.swift
Labels: bugfix

#339 feat: Swipe 이동범위에 따른 Background Color 적용
  Molio/Source/Domain/Entity/RGBAColor.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat

#343 bugfix: 맨 처음 메인 화면에 진입하는 경우 필터가 제대로 적용되지 않는 문제 해결 (#342)
  Molio/Source/Domain/Entity/RandomMusicDeck/DefaultRandomMusicDeck.swift
Labels: bugfix

#344 refactor: 프로필, 설정 등의 디자인 레이아웃 수정, 앱로고 폰트 수정
  Molio.xcodeproj/project.pbxproj
  Molio/Resource/Font/GmarketSansTTFBold.ttf
  Molio/Resource/Font/GmarketSansTTFLight.ttf
  Molio/Resource/Font/GmarketSansTTFMedium_2.ttf
  Molio/Resource/Info.plist
  Molio/Source/Presentation/Community/UserProfile/View/ProfileImageView.swift
  Molio/Source/Presentation/Community/UserProfile/View/UserProfileView.swift
  Molio/Source/Presentation/Login/View/LoginViewController.swift
  Molio/Source/Presentation/MyInfo/View/ChangeProfileImageView.swift
  Molio/Source/Presentation/Setting/View/ProfileItemView.swift
  Molio/Source/Presentation/Setting/View/SettingTextItemView.swift
  Molio/Source/Presentation/Splash/View/SplashViewController.swift
Labels: refactor

#352 bugfix: 메인 Swipe화면 버그 수정
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
Labels: feat, bugfix

#348 bugfix: 애플 재로그인시 유저 정보가 지워지는 버그수정
  Molio/Source/Data/DataSource/Network/FirebaseService/DefaultFirebaseAuthService.swift
  Molio/Source/Data/DataSource/Network/FirebaseService/Protocol/AuthService.swift
  Molio/Source/Data/Repository/DefaultAuthStateRepository.swift
  Molio/Source/Domain/RepositoryInterface/AuthStateRepository.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/DefaultManageAuthenticationUseCase.swift
  Molio/Source/Domain/UseCase/ManageAuthenticationUseCase/ManageAuthenticationUseCase.swift
  Molio/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  MolioTests/DefaultCurrentUserIdUseCaseTests.swift
  MolioTests/Test Double/Mock/DataSource/MockAuthService.swift
Labels: bugfix

#355 refactor: 카드 스와이프 임계값 수정
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
Labels: refactor

#357 feat: 인스타 공유 버튼 제거
  Molio/Source/Presentation/ExportPlaylist/View/ExportPlaylistImage/ExportPlaylistImageView.swift
Labels: feat

#353 refactor: 기타 자잘한 개선
  Molio.xcodeproj/project.pbxproj
  Molio/Source/App/SceneDelegate.swift
  Molio/Source/Data/DataSource/Network/MusicKitService/DefaultMusicKitService.swift
  Molio/Source/Presentation/FriendPlaylistDetailView/ViewModel/SelectPlaylistToExportFriendMusicViewModel.swift
  Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
  Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
  Molio/Source/Util/Extension/UIKit/UIViewController/showAlert.swift
Labels: enhancement
